apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: reddit
    component: mongo
    release: {{ .Release.Name }}
    comment-db: "true"
    post-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        release: {{ .Release.Name }}
        post-db: "true"
        comment-db: "true"
    spec:
      containers:
      - image: {{ template "mongo.container" . }}
        name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        emptyDir: {}
