apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: reddit
    component: mongo
    release: {{ .Release.Name }}
    comment-db: "true"
    post-db: "true"
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: reddit
    component: mongo
    comment-db: "true"
    post-db: "true"
    release: {{ .Release.Name }}
