# ui/Dockerfile.alpine

FROM ruby:2-alpine

RUN apk add --no-cache build-base=0.5-r3 ruby-bundler=2.3.14-r1 && \
  rm -rf /var/cache/apk/*

ENV APP_HOME /app

# [Добавляем ключ -p на случай, если путь будет /app/ui, например]
RUN mkdir -p $APP_HOME/view
WORKDIR $APP_HOME

COPY Gemfile* *.rb *.ru $APP_HOME/
COPY views/* $APP_HOME/views/
RUN bundle update --bundler

ENV POST_SERVICE_HOST post
ENV POST_SERVICE_PORT 5000
ENV COMMENT_SERVICE_HOST comment
ENV COMMENT_SERVICE_PORT 9292

CMD ["puma"]
