# comment/Dockerfile

FROM ruby:2-alpine

RUN apk add --no-cache build-base=0.5-r3 ruby-bundler=2.3.14-r1 && \
  rm -rf /var/cache/apk/*

ENV APP_HOME /app

RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

COPY VERSION *.rb config.ru Gemfile* $APP_HOME/

RUN bundle update --bundler

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
