version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.4.0
    ports:
      - "5601:5601"

  post_db:
    image: "mongo:5.0"
    volumes:
     - ./post_db:/data/db
    networks:
     - back_net

  ui:
    image: "${USERNAME}/ui:${UI_VERSION}"
    ports:
     - ${UI_PORT}:9292/tcp
    networks:
     - front_net

  post:
    image: "${USERNAME}/post:${POST_VERSION}"
    networks:
     - front_net
     - back_net
     - default
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: "${USERNAME}/comment:${COMMENT_VERSION}"
    networks:
     - front_net
     - back_net

volumes:
  post_db:

networks:
  front_net:
  back_net:
