# FILE="docker-compose.yml"
FILE="./docker-compose-logging-2-0.yml"

up:
	docker-compose -f ${FILE} up -d
down:
	docker-compose -f ${FILE} down
ps:
	docker-compose ps
logs:
	docker-compose logs -f post
