kubectl delete  -f ./comment-deployment.yml
kubectl delete  -f ./comment-mongodb-service.yml
kubectl delete  -f ./comment-service.yml
kubectl delete  -f ./mongo-deployment.yml
kubectl delete  -f ./post-deployment.yml
kubectl delete  -f ./post-mongodb-service.yml
kubectl delete  -f ./post-service.yml
kubectl delete  -f ./ui-deployment.yml
kubectl delete  -f ./ui-service.yml
