# src/docker-compose.yml

version: "3.3"

services:
  post_db:
    image: "mongo:latest"
    volumes:
     - post_db:/data/db
    networks:
     - back_net
  ui:
    # build: ./ui
    image: "${USERNAME}/ui:${UI_VERSION}"
    volumes:
      - ./ui:/app
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
    command: ["puma", "--debug", "-w", "2"]
  post:
    # build: ./post-py
    image: "${USERNAME}/post:${POST_VERSION}"
    volumes:
      - ./post-py:/app
    networks:
      - front_net
      - back_net
  comment:
    # build: ./comment
    image: "${USERNAME}/comment:${COMMENT_VERSION}"
    volumes:
      - ./comment:/app
    networks:
      - front_net
      - back_net
    command: ["puma", "--debug", "-w", "2"]

volumes:
  post_db:

networks:
  front_net:
  back_net:
