build:
	cd post-py && make build && cd -
	cd comment && make build && cd -
	cd ui && make build && cd -
clean:
	cd post-py && make build && cd -
	cd comment && make build && cd -
	cd ui && make build && cd -
run:
	. ./scripts/run.sh
